### ISSUE TITLE
Need to write easy to follow instruction

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/first-contributions#1]
I have linked to a video tutorial to learn how to contribute for first timers but I think we should also have a easy to follow written instruction.

**Comment by mhmohona** [comment]
@ratanparai bhaia, what if we add some lines in বাংলা with english also? It will be easy to understand for everyone. 
I can help to translate those in বাংলা

**Comment by ratanparai** [comment]
Thanks, @mhmohona. it will be very helpful for many of us. @kajal-alpha also want to help to translate `CONTRIBUTING` guide in Bengali. 

I hope I can finish writing a structure before **Sunday**. I will let you know when there is something to work on.

**Comment by mhmohona** [comment]
My pleasure.

**Comment by ratanparai** [comment]
I start working on `CONTRIBUTING.md` file #12

My first priority is writing easy to follow step by step guide so that everyone can start without much effort, Please feel free to review the pull request

**Comment by ratanparai** [comment]
I am closing this issue. For any further discussion about Bengali translation please follow issue #15
