### ISSUE TITLE
Add where to contribute in  `README.md` file

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/first-contributions#13]
Sadly there is no direct instruction now in `README.md` which file you should edit and send a pull request to.

I think there should be a heading with `Where to Contribute` and under that write few lines to indicate that first timer should edit `Contributing.md` file and entry their **name** and URL in the format of `[Name](URL)` 

> **Note:** To know more about markdown, read [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by mahedee** [comment]
So, you want to mean, we need to modify readme.md file and need to write a section "Where to contribute", isn't it?

**Comment by ratanparai** [comment]
@mahedee yes

**Comment by ratanparai** [comment]
closed via 2882338009a510f79e0c9baba697f3a53910297b
