### ISSUE TITLE
Open source contribution guideline

### ISSUE THREAD

**Issue by mahedee** [OpenCodeFoundation/first-contributions#16]
Prepare a documents "How to contribute in an open source project. It should be step by step approach.
For example:

- [ ] Step 1: Fork the repository : should have a clear text, how to fork.
- [ ] Step 2: Create branch : should have clear guideline how many branch should have.
- [ ] Step 3: How to push new changes
- [ ] Step 4: How to create pull request
- [ ] Step 5: How to accept pull request (as a maintainer)

**Comment by ratanparai** [comment]
Already provided in [CONTRIBUTING.md](https://github.com/OpenCodeFoundation/first-contributions/blob/master/CONTRIBUTING.md) file
